RESULTS_WANTED_DEFAULT = 30
SCRAPE_LOCATION = "Germany"
SCRAPE_DISTANCE_MILES = 31
SCRAPE_HOURS_OLD = 1
PROFILE_SCRAPE_INTERVAL_SECONDS = 60 * 60

LINKEDIN_OUTPUT_COLUMNS = [
    "id",
    "title",
    "description",
    "job_level",
    "company_industry",
    "date_posted",
    "job_url",
    "company",
    "location",
    "job_type",
]

LINKEDIN_AFTER_FILTER_COLUMNS = [
    "job_level",
    "title",
    "date_posted",
    "company",
    "location",
    "company_industry",
    "job_url",
    "job_board",
]

INDEED_OUTPUT_COLUMNS = [
    "title",
    "description",
    "company_industry",
    "date_posted",
    "job_url",
    "company",
    "location",
    "job_type",
]

INDEED_AFTER_FILTER_COLUMNS = [
    "title",
    "date_posted",
    "company",
    "location",
    "company_industry",
    "job_url",
    "job_board",
]
JOB_BOARD_INDEED = "Indeed"
JOB_BOARD_LINKEDIN = "Linkedin"

GERMAN_REQUIRED_PATTERNS = [
    r"\b(?:c1|c2)[- ]?(?:niveau|level)?[- ]?(?:deutsch|german)\b",
    r"\b(?:deutsch|german)[- ]?(?:c1|c2)\b",
    r"\b(?:mindestens|at least|minimum|min\.? )\s*(?:c1|c2)\b.{0,30}\b(?:deutsch|german)\b",
    r"\b(?:deutsch|german)\b.{0,30}\b(?:mindestens|at least|minimum|min\.? )\s*(?:c1|c2)\b",
    r"\b(?:deutschkenntnisse|german language skills?)\b.{0,30}\b(?:c1|c2)\b",
    r"\b(?:c1|c2)\b.{0,30}\b(?:deutschkenntnisse|german language skills?)\b",
    r"\b(?:flie(?:ß|ss)end|verhandlungssicher|muttersprachlich)\b.{0,40}\bdeutsch\b",
    r"\bdeutsch\b.{0,40}\b(?:flie(?:ß|ss)end|verhandlungssicher|muttersprachlich)\b",
    r"\b(?:flie(?:ß|ss)ende|verhandlungssichere|muttersprachliche)\s+deutschkenntnisse\b",
    r"\bdeutschkenntnisse\b.{0,30}\b(?:flie(?:ß|ss)end|verhandlungssicher|muttersprachlich)\b",
    r"\b(?:fluent|business[- ]fluent|native(?:[- ]level)?|near[- ]native)\b.{0,30}\bgerman\b",
    r"\bgerman\b.{0,30}\b(?:fluent|business[- ]fluent|native(?:[- ]level)?|near[- ]native)\b",
    r"\b(?:fluent|business[- ]fluent|native(?:[- ]level)?|near[- ]native)\s+german(?:\s+skills?)?\b",
    r"sprichst\s+(?:flie[sß]end|sehr gut|gut)\s+deutsch",
    r"gut und sprichst\s+flie[sß]end\s+deutsch",
    r"\bdeutsch\s*[:(]\s*(?:c1|c2|flie(?:ß|ss)end|verhandlungssicher|muttersprachlich|gut|sehr gut)\b",
    r"\b(?:sie\s+sprechen|du\s+sprichst|sie\s+beherrschen|du\s+beherrschst)\s+(?:(?:flie(?:ß|ss)end|gut|sehr gut|verhandlungssicher)\s+)?deutsch\b",
    r"\bbeherrschung\s+der\s+deutschen\s+sprache\b",
    r"\bdeutsch\s+als\s+muttersprache\b",
    r"\bdeutsch(?:kenntnisse)?\s+auf\s+muttersprachlichem?\s+niveau\b",
    r"erforderliche sprachen[\s\S]{0,80}\bdeutsch\b",
    r"sprachkenntnisse[\s\S]{0,80}\bdeutsch\b",
    r"\bdeutsch(?:-|[ \-])?und[\s\S]{0,40}\benglisch(?:kenntnisse)?\b",
    r"\b(?:gut|gute|sehr gut|sehr gute|ausgezeichnet|ausgezeichnete|exzellent|exzellente|solide|fundiert|fundierte|sicher|sichere|kommunikationssicher|kommunikationssichere)\s+deutschkenntnisse\b",
    r"\bguten\s+deutschkenntnisse\b",
    r"\bsehr\s+guten\s+deutschkenntnisse\b",
    r"\bdeutschkenntnisse\b.{0,30}\b(?:gut|gute|sehr gut|sehr gute|ausgezeichnet|ausgezeichnete|exzellent|exzellente|solide|fundiert|fundierte|sicher|sichere|kommunikationssicher|kommunikationssichere)\b",
    r"\b(?:gut|gute|sehr gut|sehr gute)\s+deutsch\b",
    r"\bdeutsch\b.{0,20}\b(?:gut|gute|sehr gut|sehr gute)\b",
    r"\b(?:gut|gute|sehr gut|sehr gute|sicher|sichere|fundiert|fundierte)\s+kenntnisse\s+der\s+deutschen\s+sprache\b",
    r"\bkenntnisse\s+der\s+deutschen\s+sprache\b.{0,30}\b(?:gut|gute|sehr gut|sehr gute|sicher|sichere|fundiert|fundierte)\b",
    r"\b(?:gut|gute|sehr gut|sehr gute)\s+kenntnisse\s+in\s+deutsch\b",
    r"\bdeutschkenntnisse\s+auf\s+(?:gutem|sehr gutem|sicherem|professionellem)\s+niveau\b",
    r"\b(?:gute|sehr gute|ausgezeichnete|flie(?:ß|ss)ende)\s+sprachkenntnisse\s+in\s+deutsch\b",
    r"\bsprachkenntnisse\b.{0,20}\bin\s+deutsch\b",
    r"\bgerman\s+language\s+skills\b",
    r"\bfluency\s+in\s+german\b",
    r"\b(?:good|very good|strong|excellent|solid)\s+german(?:\s+language)?\s+skills\b",
    r"\bgerman(?:\s+language)?\s+skills\b.{0,30}\b(?:good|very good|strong|excellent|solid)\b",
    r"\bproficient\s+in\s+german\b",
    r"\bprofessional(?:ly)?\s+proficient\s+in\s+german\b",
    r"\bstrong\s+command\s+of\s+german\b",
    r"\bgood\s+command\s+of\s+german\b",
    r"\bdeutsch\b.{0,20}\bin\s+wort\s+und\s+schrift\b",
    r"\bin\s+wort\s+und\s+schrift\b.{0,20}\bdeutsch\b",
    r"\bdeutschkenntnisse\b.{0,30}\bin\s+wort\s+und\s+schrift\b",
    r"\bin\s+wort\s+und\s+schrift\b.{0,30}\bdeutschkenntnisse\b",
    r"\b(?:gute|sehr gute|flie(?:ß|ss)ende|verhandlungssichere)\s+deutschkenntnisse\s+in\s+wort\s+und\s+schrift\b",
    r"\b(?:written\s+and\s+spoken|oral\s+and\s+written)\s+german\b",
    r"\b(?:good|very good|strong|excellent)\s+(?:written\s+and\s+spoken|oral\s+and\s+written)\s+german\b",
    r"\b(?:written\s+and\s+spoken|oral\s+and\s+written)\s+german\b.{0,20}\b(?:good|very good|strong|excellent)\b",
    r"\bgerman(?:\s+language)?\s+skills?\s+(?:is|are)?\s*(?:required|mandatory|must|essential|necessary)\b",
    r"\b(?:required|mandatory|must|essential|necessary)\b.{0,30}\bgerman(?:\s+language)?\s+skills?\b",
    r"\bdeutsch(?:kenntnisse)?\s+(?:sind\s+)?(?:zwingend|unbedingt\s+)?(?:erforderlich|vorausgesetzt|voraussetzung|notwendig|pflicht)\b",
    r"\b(?:zwingend|unbedingt)\b.{0,20}\bdeutsch(?:kenntnisse)?\b",
    r"\b(?:erforderlich|voraussetzung|notwendig|pflicht)\b.{0,30}\bdeutsch(?:kenntnisse)?\b",
    r"\bdeutsch(?:kenntnisse)?\b.{0,30}\b(?:erforderlich|voraussetzung|notwendig|pflicht)\b",
    r"\bdeutsch\s+als\s+(?:unternehmenssprache|arbeitssprache|firmensprache)\b",
    r"\b(?:arbeitssprache|unternehmenssprache|firmensprache)\s+(?:ist\s+)?deutsch\b",
    r"\bdeutsch\s+ist\s+die\s+(?:arbeitssprache|unternehmenssprache|firmensprache)\b",
    r"\b(?:team|kommunikation|kommunizieren|austausch|abstimmung)\b.{0,30}\bauf\s+deutsch\b",
    r"\bdeutschsprachig(?:e[nrms]?)?\s+(?:kommunikation|umfeld|team|umgebung|arbeitsumfeld)\b",
    r"\b(?:gute|sehr gute|flie(?:ß|ss)ende)\b.{0,20}\bdeutsch-?\s*und\s*englischkenntnisse\b",
    r"\b(?:gute|sehr gute|flie(?:ß|ss)ende)\b.{0,20}\benglisch-?\s*und\s*deutschkenntnisse\b",
    r"\bflie(?:ß|ss)ende\s+deutsch-?\s*und\s*(?:sehr\s+guten|guten|sehr\s+gute|gute)\s+englischkenntnisse\b",
    r"\b(?:good|very good|fluent)\s+german\s+and\s+english\b",
    r"\b(?:good|very good|fluent)\s+english\s+and\s+german\b",
]
